name: wale
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - healpy
  - jupyter
  - notebook
  - ipykernel
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - pyccl
  - mpmath
  - jax
  - pytest
  - pytest-cov
  - distinctipy
  - camb
  - numba
  - scikit-image
  - joblib
  - astropy
  - black
  - pip:
      - tqdm
      - classy
      - fast-pt
