name: CI

on:
  push:       { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and test deps
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
      
      - name: Run black (code formatting check)
        run: |
          black --check src/
